<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Final Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Final Project</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            COUNTRY Completion Year
             &lt;char&gt;           &lt;num&gt;
1: Africa, regional              NA
2: Africa, regional              NA
3: Africa, regional            2021
4:          Algeria            2021
5:          Algeria              NA
6:          Algeria            2021
                                                                                                                                        Title
                                                                                                                                       &lt;char&gt;
1:                                   ICBC contributes to $1.2 billion syndicated loan to Afreximbank for on-lending purposes in December 2021
2: Chinese Government signs agreement with UN World Food Program to provide food aid to Benin, Liberia and the Republic of Congo in July 2021
3:           Chinese Mission to the African Union donates medical supplies to the United Nations Economic Commission for Africa in March 2021
4:                     Chinese Government donates 200,000 Sinopharm vaccines worth $3.6 million in February 2021 (Linked to Project ID#97169)
5:                                                                                  Hubei Health Comission sends 26th medical team to Algeria
6:   Chinese Government donates 3.2 million Sinovac Covid-19 vaccine doses worth $57.6 million in September 2021 (Linked to Project ID#94808)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Description
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              &lt;char&gt;
1:                                                                                                                                                                           On December 21, 2021, the African Export-Import Bank (Afreximbank) signed a $1.2 billion syndicated term loan facility agreement with a group of 22 banks, including the Industrial and Commercial Bank of China (ICBC). The loan carried a 3-year maturity and unknown interest rate. First Abu Dhabi Bank PJSC, Rand Merchant Bank, a division of FirstRand Bank Limited (London Branch) and Standard Chartered Bank acted as joint Global Coordinators, Mandated Lead Arrangers and Bookrunners on the Facility. Standard Chartered Bank acted as Documentation Agent and is the Facility Agent for the transaction.
2: On July 29, 2021, the Chinese Government signed an agreement with the United Nations World Food Programme (WFP) to provide food aid to Benin, Liberia, and the Republic of Congo. The purpose of this agreement is to provide food assistance to vulnerable groups in the three countries. The agreement indicates that China will use its South-South Cooperation Fund to finance the project and the WFP will help to implement the project. Implementation details have yet to be found.   A signing ceremony was held virtually for this agreement. Luo Zhaohui, the Chairman of the China International Development Cooperation Agency (CIDCA), and David Beasley, the Executive Director of the World Food Programme (WFP), attended the ceremony and signed the food assistance agreement.
3:                                                                                                                                                                                                                                                                                                                                                                                           On March 24, 2021, the Chinese Mission to the African Union (AU) donated medical supplies for the prevention and treatment of Covid-19 to the United Nations Economic Commission for Africa (UNECA). The donation included thermometers, oxygen generators, isolation gowns, ventilators, surgical masks and other personal protective equipments (PPE). The UNECA is located in Addis Ababa, Ethiopia.
4:                                                                                                                                                                                                                                               On February 10, 2021, Chinese Foreign Minister Wang Yi confirmed a donation of 200,000 Sinopharm vaccine doses (worth an estimated $3.6 million) on a phone call with Algerian Foreign Minister Boukadoum. The vaccines arrived on February 24, 2021 and were handed over in a ceremony at Algeria's Boufarik military airport (as captured via Project ID#94808).   Then, in September 2021, the Chinese Government donated 3.2 million doses of the Sinovac Covid-19 vaccine worth an estimated $57.6 million (as captured via Project ID#97169).
5:                                                                                                                                                                                                                                                                                                                                           In August and Septermber 2021 the 26th medical team sent by the Hubei Health Comission arrived in Algeria. The team had 81 total members split across 8 smaller teams. By June 2022, the medical team had received 72,000 patients, admitted 45,000 hospitalizations, performed 17,000 operations of various types, and delivered 25,000 births. The team also provided medical services to overseas Chinese and employees of Chinese-funded companies.
6:                                                                                                                                                                                                                                               On February 10, 2021, Chinese Foreign Minister Wang Yi confirmed a donation of 200,000 Sinopharm vaccine doses (worth an estimated $3.6 million) on a phone call with Algerian Foreign Minister Boukadoum. The vaccines arrived on February 24, 2021 and were handed over in a ceremony at Algeria's Boufarik military airport (as captured via Project ID#94808).   Then, in September 2021, the Chinese Government donated 3.2 million doses of the Sinovac Covid-19 vaccine worth an estimated $57.6 million (as captured via Project ID#97169).
                 Status Region   Amount
                 &lt;char&gt; &lt;char&gt;    &lt;num&gt;
1: Pipeline: Commitment Africa 54545454
2: Pipeline: Commitment Africa       NA
3:           Completion Africa       NA
4:           Completion Africa  3600000
5:       Implementation Africa       NA
6:           Completion Africa 57600000</code></pre>
</div>
</div>
<p>Introduction:</p>
<p>Over the past century, China has become an increasingly important player in the politics and economic development of African countries. The Sino-African relationship, which began in the 1950s through political diplomatic relations rooted in third world solidarity has expanded into a multifaceted economic partnership. This newfound association poses tremendous implications for the US in its role in global governance and affairs on the continent, prompting a great deal of discourse in international relations. Two dominant schools of thought emerge as the framework through which this engagement is interpreted—those who view Chinese investment as a neo-colonial form of extractivism and those who see it as a mutually beneficial South-South partnership offering an alternative to Western conditional aid. As China and the US continue to compete for economic and geopolitical influence, African nations find themselves positioned in the center of the global tug of war, leveraging partnerships for developmental gain and wrestling with concerns of debt sustainability, democracy, and resource control. Prevailing narratives from the West would have it that Chinese investments are deleterious to democratic norms and governance structures in Africa, often portraying them as enabling authoritarian regimes, exacerbating corruption, and undermining transparency. The broader complexity of this debate is reflected in the differing stances of African politicians, with some embracing Chinese investment as a necessary catalyst for development, while others express concerns over debt dependency and governance implications. However, one crucial perspective that remains underexplored in the literature is that of African people themselves. This project investigates how African citizens perceive Chinese loans, asking: How do these perceptions vary based on the amount of Chinese investment their countries receive? It further examines whether these perceptions differ by educational attainment, positing that citizens with greater access to information may evaluate foreign influence more critically. By accounting for both national-level exposure and individual-level variation, the analysis seeks to illuminate how structural and informational factors interact to shape public sentiment in the context of global power competition.This paper aims to fill the void of African perspectives in the ongoing debate about the consequence of increased Chinese partnership on the continent. Moving beyond state-centric and Western-dominated narratives, this analysis seeks to highlight how Africans themselves interpret, navigate, and respond to Chinese engagement—whether as an opportunity for economic transformation, a source of new dependencies, or something more nuanced. Much of the scrutiny surrounding China’s role in Africa stems from its ideological divergence from the United States. Early partnerships, formed during the Cold War, were grounded in shared anti-imperialist sentiment and a rejection of Western dominance, establishing relationships that prioritized sovereignty over liberal democratic values. This ideological contrast remains relevant today, as China’s policy of non-interference and emphasis on state-led development continues to clash with the U.S.’s democracy-promotion agenda (<span class="citation" data-cites="saiia2025">@saiia2025</span>). These divergent worldviews are reflected in their approaches to economic engagement: China primarily offers loans and sometimes infrastructure-for-resource deals, while the U.S. tends to favor grant-based aid linked to governance and democratic reforms. While dominant Western narratives often portray Chinese loans as uniformly burdensome or exploitative, scholars argue that the reality is more nuanced. Although risks are present, Chinese lending practices vary significantly depending on the lender, the borrowing country, and the nature of the project (<span class="citation" data-cites="alden2021">@alden2021</span>). While Chinese creditors are a notable part of Africa’s debt landscape, their overall contribution is relatively modest and not the primary cause of debt distress on the continent (<span class="citation" data-cites="alden2021">@alden2021</span>). Beyond economics, China’s expanding presence is increasingly viewed as a challenge to U.S. soft power, with scholars and policymakers warning of a potential resurgence in authoritarian influence as China deepens its foothold across the continent. Geopolitical competition has real consequences, beyond economic benefits it redefines how individuals perceive development projects and foreign direct investment. This competition shapes not only policy decisions at the national level but also public opinion, influencing how communities evaluate the legitimacy, intentions, and long-term value of foreign involvement in their local development (<span class="citation" data-cites="springman2025">@springman2025</span>). The dominant narrative surrounding partnerships in Africa often frames them as a zero-sum contest between global powers—primarily the United States and China. Such portrayals are overly reductive and leave little room for nuance in understanding African agency. Taking African perspectives seriously requires moving beyond this binary thinking. The continent’s engagement with, and attraction to, China’s development model should not be interpreted as a rejection of democratic or competitive norms. Rather, these choices are often shaped less by ideology and more by pragmatic assessments of what is perceived to be most beneficial (<span class="citation" data-cites="Benabdallah2023">@Benabdallah2023</span>). Any research occurring about the African continent cannot ignore its historical position at the center of global struggles from colonialism to the Cold War and now the current era of multipolarity. This long standing engagement with competing global powers has not only shaped the political and economic structures of African states, but also informs how contemporary partnerships are evaluated and pursued. Understanding these dynamics requires a shift away from viewing African states as passive recipients of influence, and instead recognizing their strategic agency in navigating an evolving global order. Building on work done in analyzing the role of China’s economic influence in the competitive global landscape– and seeking to complicate our understanding of Chinese African relations beyond western dominated narratives– this study centers how Africans perceive China’s growing presence on the continent. It challenges the assumption that growing geopolitical competition fundamentally reshapes African nations’ preferences for aid from either China or the West. Instead, it posits that–at least in the eyes of citizens– geopolitical competition has neutral effects on the ways in which they view aid—especially given that these external pressures have long since informed the African nations engagement with global powers.</p>
<p>Theory and Hypothesis:</p>
<p>This paper examines how varying levels of Chinese foreign investment, within the context of an increasingly competitive global landscape, influence African citizens’ perceptions of foreign aid and development. Grounded in scholarship that complicates binary portrayals of Chinese-African engagement (<span class="citation" data-cites="Benabdallah2023">@Benabdallah2023</span>;<span class="citation" data-cites="taylor2006">@taylor2006</span>), this study considers that geopolitical competition is not necessarily internalized by everyday citizens. This is not because it lacks significance, but because external power struggles have historically shaped Africa’s interactions with the world. In this context, the longstanding presence of competing global powers has normalized foreign involvement, prompting citizens to evaluate aid less through ideological lenses and more through its tangible outcomes. As a result, this paper argues that perceptions of Chinese aid are shaped more by visible, material benefits than by broader geopolitical narratives. This responsiveness may be especially pronounced among individuals with lower levels of formal education, who are often more directly impacted by and attuned to localized development outcomes than abstract foreign policy dynamics. Hypothesis: In countries receiving higher levels of Chinese development finance, citizens will exhibit more favorable perceptions of Chinese foreign investment. This relationship will be stronger among individuals with lower levels of formal education. This hypothesis rests on the assumption that development in the country is what enhances the legitimacy of foreign actors, independent of concerns about national debt or sovereignty. This effect may be magnified for populations that are less exposed to critical ideological narratives. It’s clear that Chinese lending has been crucial to financing large scale projects. Therefore, it is plausible that in countries receiving higher levels of Chinese finance, citizens perceive this engagement more positively not necessarily because they prefer China ideologically, but because they see real material outcomes in their daily lives. Research Design This study uses two primary datasets: AidData’s Global Chinese Development Finance Dataset v3.0 and the Afrobarometer Merged Round 8 survey (2022), covering 34 African countries. AidData tracks 20,985 Chinese-financed development projects worth $1.34 trillion across 165 low- and middle-income countries from 2000 to 2021, with implementation data through 2023. It provides country-level indicators of Chinese investment. Afrobarometer offers nationally representative surveys of adults aged 18 and older, capturing political, economic, and social attitudes. The unit of analysis is the individual respondent (n = 15,747), with country-level investment data merged by country of residence. While the merged dataset enables a multi-level analysis of how national investment exposure interacts with individual-level characteristics, there are important limitations. Notably, neither dataset directly captures how African citizens feel about receiving Chinese investment. Instead, this study relies on a proxy variable that reflects whether respondents believe their government has borrowed too much from China—a question that signals concern but does not fully capture perceptions of the investment’s quality, intent, or impact. As such, any conclusions drawn must be interpreted with caution, given the indirect nature of the measure. The analysis is carried out using a logistic regression to model the probability of the binary outcome (yes or no). The independent variable x represents the amount of Chinese investment per country and is drawn from AidData’s Global Chinese Development Finance dataset. The dependent variable Y represents the public perception of Chinese foreign investment as either positive or negative. Question 65C from Afrobarometer round 8– “Do you think our government has borrowed too much money from China, or haven’t you heard enough to say?”— is used as a proxy for public awareness and attitudes toward Chinese development finance. This variable captures whether respondents believe their government has borrowed excessively from China, with value labels indicating ‘Yes’ (1), ‘No’ (0), ‘Not applicable’ (7), ‘Refused’ (8), ‘Don’t know’ (9), and ‘Missing’ (-1). For the purposes of this analysis, only valid responses coded as ‘Yes’ or ‘No’ are retained to construct a binary outcome. By pairing Afrobarometer perception data with verified investment records, this study provides the opportunity to assess whether public concerns about Chinese lending correlate with financial engagement on the ground.</p>
<p>Logistic Regression Model: Logit(P(Yi​=1))=β0​+β1​Xi​+β2​Z1​+β3​Z2​+⋯+βk​Zk​+ϵi​</p>
<p>The model includes several covariates to account for factors that may shape perceptions of Chinese development finance. Education captures access to political knowledge; employment status reflects socio economic positioning and potential exposure to aid benefits; trust in government gauges institutional confidence, which may influence attitudes toward foreign borrowing. These variables are measured using Afrobarometer survey items detailed in the appendix. A key limitation of this study is the potential for omitted variable bias. This arises when relevant factors that influence both the independent and dependent variables are not included in the model. Unobserved factors on the individual level, such as political ideology or exposure to foreign media, are not directly captured in the available data and mahy still influence response. While the empirical strategy accounts for this on a country to country basis, it does noy limit the risk of omitted variable bias entirely. There is also a temporal limitation, as public opinion is captured at only one point in time. This cross-sectional snapshot prevents the analysis from observing how perceptions of Chinese investment evolve in response to shifting political dynamics, project outcomes, or broader changes in the geopolitical landscape. Without longitudinal data, it is difficult to assess whether observed attitudes are stable over time or reflect short-term sentiments influenced by recent events. To strengthen causal inference, this study includes an empirical extension that restricts the sample to individuals with low formal education. By doing so, the analysis isolates variation in perception among respondents who are less likely to be exposed to elite or ideological criticism of Chinese investment. If the relationship between country-level aid and perception holds in this subgroup, it reduces concern that the main results are driven by educated elites who may be more attuned to geopolitical discourse or external media. This extension helps rule out information exposure as a confounding pathway, strengthening the claim that observed effects reflect material development impacts rather than ideological filtering. To strengthen causal inference, this study includes an empirical extension that restricts the sample to individuals with low formal education. By doing so, the analysis isolates variation in perception among respondents who are less likely to be exposed to elite or ideological criticism of Chinese investment. If the relationship between country-level aid and perception holds in this subgroup, it reduces concern that the main results are driven by educated elites who may be more attuned to geopolitical discourse or external media. This extension helps rule out information exposure as a confounding pathway, strengthening the claim that observed effects reflect material development impacts rather than ideological filtering.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script>

      function styleCell_smwnq88vxqkh27s54gn9(i, j, css_id) {
          var table = document.getElementById("tinytable_smwnq88vxqkh27s54gn9");
          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_smwnq88vxqkh27s54gn9');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_smwnq88vxqkh27s54gn9(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_smwnq88vxqkh27s54gn9");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: 12, j: 1 }, { i: 12, j: 2 },  ], css_id: 'tinytable_css_z197porfdbp2x2q23jwh',}, 
          { positions: [ { i: 18, j: 1 }, { i: 18, j: 2 },  ], css_id: 'tinytable_css_sotu8u5exwncqfo6wh1i',}, 
          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_oxnomtfin8wzfjzf8utf',}, 
          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 },  ], css_id: 'tinytable_css_nwd0rsy5sr19dq6i9uzf',}, 
          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 16, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 }, { i: 15, j: 0 }, { i: 17, j: 0 },  ], css_id: 'tinytable_css_mir44ardeg0lkp8xp5l6',}, 
          { positions: [ { i: 18, j: 0 },  ], css_id: 'tinytable_css_hzznl4tm4p5neci79r2i',}, 
          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_huz8rlka6kdpvqbe2ye8',}, 
          { positions: [ { i: 1, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 2, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 6, j: 2 }, { i: 13, j: 1 }, { i: 14, j: 1 }, { i: 15, j: 1 }, { i: 16, j: 1 }, { i: 17, j: 1 }, { i: 3, j: 2 }, { i: 6, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 7, j: 2 }, { i: 4, j: 2 }, { i: 5, j: 2 }, { i: 10, j: 2 }, { i: 11, j: 2 }, { i: 8, j: 2 }, { i: 9, j: 2 }, { i: 14, j: 2 }, { i: 15, j: 2 }, { i: 16, j: 2 }, { i: 13, j: 2 }, { i: 17, j: 2 },  ], css_id: 'tinytable_css_egbxgeqguqmpx2wajrwf',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_smwnq88vxqkh27s54gn9(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <style>
      /* tinytable css entries after */
      .table td.tinytable_css_z197porfdbp2x2q23jwh, .table th.tinytable_css_z197porfdbp2x2q23jwh { text-align: center; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_sotu8u5exwncqfo6wh1i, .table th.tinytable_css_sotu8u5exwncqfo6wh1i { text-align: center; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_oxnomtfin8wzfjzf8utf, .table th.tinytable_css_oxnomtfin8wzfjzf8utf { text-align: left; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_nwd0rsy5sr19dq6i9uzf, .table th.tinytable_css_nwd0rsy5sr19dq6i9uzf { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_mir44ardeg0lkp8xp5l6, .table th.tinytable_css_mir44ardeg0lkp8xp5l6 { text-align: left; }
      .table td.tinytable_css_hzznl4tm4p5neci79r2i, .table th.tinytable_css_hzznl4tm4p5neci79r2i { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_huz8rlka6kdpvqbe2ye8, .table th.tinytable_css_huz8rlka6kdpvqbe2ye8 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_egbxgeqguqmpx2wajrwf, .table th.tinytable_css_egbxgeqguqmpx2wajrwf { text-align: center; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_smwnq88vxqkh27s54gn9" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        </thead><caption>Table 1: Logistic Regression: Predictors of Opinion on Chinese Debt</caption>
              <tbody><tr>
                <th scope="col"> </th>
                <th scope="col">Without Region Fixed Effects</th>
                <th scope="col">With Region Fixed Effects</th>
              </tr>
        
        </tbody><tfoot><tr><td colspan="3">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td>Education: Medium</td>
                  <td>0.281***</td>
                  <td>0.090</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.046)</td>
                  <td>(0.056)</td>
                </tr>
                <tr>
                  <td>Education: High</td>
                  <td>0.259***</td>
                  <td>0.175*</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.056)</td>
                  <td>(0.069)</td>
                </tr>
                <tr>
                  <td>Employment: Looking</td>
                  <td>-0.348***</td>
                  <td>-0.080</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.056)</td>
                  <td>(0.065)</td>
                </tr>
                <tr>
                  <td>Employment: Part-time</td>
                  <td>-0.155*</td>
                  <td>0.030</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.068)</td>
                  <td>(0.078)</td>
                </tr>
                <tr>
                  <td>Trust in President: Medium</td>
                  <td>-0.054</td>
                  <td>-0.088</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.050)</td>
                  <td>(0.058)</td>
                </tr>
                <tr>
                  <td>Trust in President: High</td>
                  <td>-0.478***</td>
                  <td>-0.427***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.044)</td>
                  <td>(0.054)</td>
                </tr>
                <tr>
                  <td>Num.Obs.</td>
                  <td>15497</td>
                  <td>15497</td>
                </tr>
                <tr>
                  <td>AIC</td>
                  <td>16693.5</td>
                  <td>14819.2</td>
                </tr>
                <tr>
                  <td>BIC</td>
                  <td>16754.7</td>
                  <td>17939.8</td>
                </tr>
                <tr>
                  <td>Log.Lik.</td>
                  <td>-8338.750</td>
                  <td>-7001.618</td>
                </tr>
                <tr>
                  <td>F</td>
                  <td>43.709</td>
                  <td>4.963</td>
                </tr>
                <tr>
                  <td>RMSE</td>
                  <td>0.42</td>
                  <td>0.38</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary data frame</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">"Total Aid"</span>, <span class="st">"Education"</span>, <span class="st">"Trust in President"</span>, <span class="st">"Employment Status"</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">c</span>(<span class="fu">mean</span>(analysis_data<span class="sc">$</span>total_aid, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>           <span class="fu">mean</span>(<span class="fu">as.numeric</span>(analysis_data<span class="sc">$</span>Q97), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">mean</span>(<span class="fu">as.numeric</span>(analysis_data<span class="sc">$</span>Q41A), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>           <span class="fu">mean</span>(<span class="fu">as.numeric</span>(analysis_data<span class="sc">$</span>Q95A), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Range =</span> <span class="fu">c</span>(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="st">"$"</span>, scales<span class="sc">::</span><span class="fu">comma</span>(<span class="fu">min</span>(analysis_data<span class="sc">$</span>total_aid, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="st">" - $"</span>, scales<span class="sc">::</span><span class="fu">comma</span>(<span class="fu">max</span>(analysis_data<span class="sc">$</span>total_aid, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="fu">range</span>(analysis_data<span class="sc">$</span>Q97, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">collapse =</span> <span class="st">" - "</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="fu">range</span>(analysis_data<span class="sc">$</span>Q41A, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">collapse =</span> <span class="st">" - "</span>),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="fu">range</span>(analysis_data<span class="sc">$</span>Q95A, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">collapse =</span> <span class="st">" - "</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Standard Deviation</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">sd</span>(analysis_data<span class="sc">$</span>total_aid, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">sd</span>(<span class="fu">as.numeric</span>(analysis_data<span class="sc">$</span>Q97), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">sd</span>(<span class="fu">as.numeric</span>(analysis_data<span class="sc">$</span>Q41A), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">sd</span>(<span class="fu">as.numeric</span>(analysis_data<span class="sc">$</span>Q95A), <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="fu">gt</span>(summary_stats) <span class="sc">|&gt;</span> </span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"Descriptive Statistics of Key Variables"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="qywkhamhtv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#qywkhamhtv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#qywkhamhtv thead, #qywkhamhtv tbody, #qywkhamhtv tfoot, #qywkhamhtv tr, #qywkhamhtv td, #qywkhamhtv th {
  border-style: none;
}

#qywkhamhtv p {
  margin: 0;
  padding: 0;
}

#qywkhamhtv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#qywkhamhtv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#qywkhamhtv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#qywkhamhtv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#qywkhamhtv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qywkhamhtv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qywkhamhtv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qywkhamhtv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#qywkhamhtv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#qywkhamhtv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#qywkhamhtv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#qywkhamhtv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#qywkhamhtv .gt_spanner_row {
  border-bottom-style: hidden;
}

#qywkhamhtv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#qywkhamhtv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#qywkhamhtv .gt_from_md > :first-child {
  margin-top: 0;
}

#qywkhamhtv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#qywkhamhtv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#qywkhamhtv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#qywkhamhtv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#qywkhamhtv .gt_row_group_first td {
  border-top-width: 2px;
}

#qywkhamhtv .gt_row_group_first th {
  border-top-width: 2px;
}

#qywkhamhtv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qywkhamhtv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#qywkhamhtv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#qywkhamhtv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qywkhamhtv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qywkhamhtv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#qywkhamhtv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#qywkhamhtv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#qywkhamhtv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qywkhamhtv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qywkhamhtv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qywkhamhtv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qywkhamhtv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qywkhamhtv .gt_left {
  text-align: left;
}

#qywkhamhtv .gt_center {
  text-align: center;
}

#qywkhamhtv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#qywkhamhtv .gt_font_normal {
  font-weight: normal;
}

#qywkhamhtv .gt_font_bold {
  font-weight: bold;
}

#qywkhamhtv .gt_font_italic {
  font-style: italic;
}

#qywkhamhtv .gt_super {
  font-size: 65%;
}

#qywkhamhtv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#qywkhamhtv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#qywkhamhtv .gt_indent_1 {
  text-indent: 5px;
}

#qywkhamhtv .gt_indent_2 {
  text-indent: 10px;
}

#qywkhamhtv .gt_indent_3 {
  text-indent: 15px;
}

#qywkhamhtv .gt_indent_4 {
  text-indent: 20px;
}

#qywkhamhtv .gt_indent_5 {
  text-indent: 25px;
}

#qywkhamhtv .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#qywkhamhtv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<th colspan="4" class="gt_heading gt_title gt_font_normal gt_bottom_border">Descriptive Statistics of Key Variables</th>
</tr>
<tr class="gt_col_headings even">
<th id="Variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variable</th>
<th id="Mean" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Mean</th>
<th id="Range" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Range</th>
<th id="Standard-Deviation" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Standard Deviation</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Total Aid</td>
<td class="gt_row gt_right" headers="Mean">2.063356e+10</td>
<td class="gt_row gt_right" headers="Range">$368,636,433 - $108,911,480,026</td>
<td class="gt_row gt_right" headers="Standard Deviation">3.022806e+10</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Education</td>
<td class="gt_row gt_right" headers="Mean">4.290087e+00</td>
<td class="gt_row gt_right" headers="Range">-1 - 99</td>
<td class="gt_row gt_right" headers="Standard Deviation">4.404936e+00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Trust in President</td>
<td class="gt_row gt_right" headers="Mean">1.589128e+00</td>
<td class="gt_row gt_right" headers="Range">-1 - 9</td>
<td class="gt_row gt_right" headers="Standard Deviation">1.347424e+00</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Employment Status</td>
<td class="gt_row gt_right" headers="Mean">1.316378e+00</td>
<td class="gt_row gt_right" headers="Range">-1 - 9</td>
<td class="gt_row gt_right" headers="Standard Deviation">1.230043e+00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Findings</p>
<p>Figure 1 displays a bar chart visualizing the relationship between the average Chinese investment and public perception of Chinese debt. The plot shows that, on average, those who perceive excessive borrowing report slightly lower investment from China compared to those who do not view the borrowing as excessive. The “Yes” group has an average investment of around 15 billion USD, while the “No” group has an average investment of approximately 17 billion USD. Although there is a discernible difference, the error bars suggest that there is considerable variability within each group, implying that while a trend exists, it may not be overwhelmingly large. The relationship between public perception of Chinese debt and investment appears to be modest, highlighting the need for further exploration of additional factors that could influence public views on this matter. The regression analysis (Table 1) examines predictors of public opinion on Chinese debt, focusing on education, employment status, and trust in the president. Education level significantly affects perceptions, with those having medium or high education more likely to perceive excessive borrowing. Specifically, individuals with medium education are 0.281 more likely, while those with higher education are 0.259 more likely to hold this view. These results indicate that education is an important factor in shaping opinions about government borrowing from China. Employment status also plays a role, with job-seeking individuals (-0.348) less likely to view borrowing as excessive, suggesting that economic circumstances may influence perceptions. Those in part-time employment show a weaker negative effect (-0.155), reflecting the idea that individuals focused on immediate economic concerns may not prioritize foreign debt issues. Trust in the president is another key factor, with higher trust leading to less critical views on Chinese debt. High trust in the president correlates with a -0.478 reduction in the likelihood of perceiving excessive borrowing. The regression results are statistically significant, with education and trust in the president showing strong effects at the 1% level, while employment status is significant at the 5% level. The findings underscore the importance of education and trust in shaping public perceptions of Chinese debt, with substantial effects from these variables. Despite the strong effects, the large sample size (15,497) suggests sufficient statistical power, though unobserved factors could still influence perceptions.</p>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script>

      function styleCell_w16gmwunlhet9gnpip6m(i, j, css_id) {
          var table = document.getElementById("tinytable_w16gmwunlhet9gnpip6m");
          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_w16gmwunlhet9gnpip6m');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_w16gmwunlhet9gnpip6m(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_w16gmwunlhet9gnpip6m");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_xnri2mfzggsbyu6n3zq0',}, 
          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_ts32y4m0wfv2renniu2h',}, 
          { positions: [ { i: 10, j: 1 },  ], css_id: 'tinytable_css_rxuxok68ov109fvxd8er',}, 
          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 14, j: 1 }, { i: 11, j: 1 }, { i: 12, j: 1 }, { i: 13, j: 1 }, { i: 15, j: 1 },  ], css_id: 'tinytable_css_qh0b5yqxbwiaa2n23yg3',}, 
          { positions: [ { i: 16, j: 0 },  ], css_id: 'tinytable_css_pn9nwib8k68q2cgief5i',}, 
          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 14, j: 0 }, { i: 11, j: 0 }, { i: 12, j: 0 }, { i: 13, j: 0 }, { i: 15, j: 0 },  ], css_id: 'tinytable_css_b1vfx22jpzwzv65min4x',}, 
          { positions: [ { i: 16, j: 1 },  ], css_id: 'tinytable_css_ad9lfszpawd1nbzq6xya',}, 
          { positions: [ { i: 10, j: 0 },  ], css_id: 'tinytable_css_1xjhqjg03bt6qx3gaquz',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_w16gmwunlhet9gnpip6m(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <style>
      /* tinytable css entries after */
      .table td.tinytable_css_xnri2mfzggsbyu6n3zq0, .table th.tinytable_css_xnri2mfzggsbyu6n3zq0 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_ts32y4m0wfv2renniu2h, .table th.tinytable_css_ts32y4m0wfv2renniu2h { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_rxuxok68ov109fvxd8er, .table th.tinytable_css_rxuxok68ov109fvxd8er { text-align: center; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_qh0b5yqxbwiaa2n23yg3, .table th.tinytable_css_qh0b5yqxbwiaa2n23yg3 { text-align: center; }
      .table td.tinytable_css_pn9nwib8k68q2cgief5i, .table th.tinytable_css_pn9nwib8k68q2cgief5i { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_b1vfx22jpzwzv65min4x, .table th.tinytable_css_b1vfx22jpzwzv65min4x { text-align: left; }
      .table td.tinytable_css_ad9lfszpawd1nbzq6xya, .table th.tinytable_css_ad9lfszpawd1nbzq6xya { text-align: center; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_1xjhqjg03bt6qx3gaquz, .table th.tinytable_css_1xjhqjg03bt6qx3gaquz { text-align: left; border-bottom: solid black 0.05em; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_w16gmwunlhet9gnpip6m" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        </thead><caption>Perception of Chinese Loans by Education × Debt Level Groups</caption>
              <tbody><tr>
                <th scope="col"> </th>
                <th scope="col">(1)</th>
              </tr>
        
        </tbody><tfoot><tr><td colspan="2">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td>LowEd × HighDebt</td>
                  <td>0.140+</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.072)</td>
                </tr>
                <tr>
                  <td>HighEd × LowDebt</td>
                  <td>0.309***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.079)</td>
                </tr>
                <tr>
                  <td>HighEd × HighDebt</td>
                  <td>0.518***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.082)</td>
                </tr>
                <tr>
                  <td>Employment: Looking</td>
                  <td>-0.314***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.080)</td>
                </tr>
                <tr>
                  <td>Employment: Part-time</td>
                  <td>-0.126</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.096)</td>
                </tr>
                <tr>
                  <td>Num.Obs.</td>
                  <td>7557</td>
                </tr>
                <tr>
                  <td>AIC</td>
                  <td>8410.1</td>
                </tr>
                <tr>
                  <td>BIC</td>
                  <td>8458.6</td>
                </tr>
                <tr>
                  <td>Log.Lik.</td>
                  <td>-4198.062</td>
                </tr>
                <tr>
                  <td>F</td>
                  <td>20.814</td>
                </tr>
                <tr>
                  <td>RMSE</td>
                  <td>0.43</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Empirical Extension:</p>
<p>Figure 2 displays the predicted probabilities of viewing Chinese loans as a problem across four education × debt group interactions: LowEd_LowDebt, LowEd_HighDebt, HighEd_LowDebt, and HighEd_HighDebt. The results demonstrate that individuals in the HighEd_HighDebt group (those with high education and a high perception of debt) have the highest predicted probability of viewing Chinese loans as a problem, approaching 84%. This is followed by the HighEd_LowDebt group, with a predicted probability of around 80%. The LowEd_LowDebt group (those with low education and a low perception of debt) has the lowest predicted probability, just below 76%, while the LowEd_HighDebt group lies between 76% and 80%. These findings suggest that education, especially when combined with perceptions of national debt, significantly influences how individuals view Chinese loans. The error bars in the plot indicate that the differences between these groups are statistically significant. For example, the HighEd_HighDebt group is predicted to have a significantly higher probability of viewing Chinese loans as problematic compared to the LowEd_LowDebt group, reinforcing the hypothesis that education and debt perception interact to shape opinions on foreign loans. This result supports the notion that access to information, represented here by education, conditions how individuals respond to foreign debt, with better-informed groups (those with higher education) showing more concern about the implications of such loans. The regression model further supports these findings, with education and debt level interacting as key determinants of individuals’ views on Chinese loans. Specifically, the predicted probabilities reveal an approximately 8% difference between the LowEd_LowDebt and HighEd_HighDebt groups, demonstrating that education significantly influences the likelihood of perceiving Chinese loans as problematic. The regression results (table 2) also show that employment status plays a role, with individuals “Looking” for work showing a statistically significant negative association with viewing Chinese loans as a problem (-0.314, ***p &lt; 0.001). It’s likely that individuals who are unemployed or seeking work may be less concerned about foreign debt, possibly because their immediate economic concerns take precedence. The part-time and full-time employment coefficients were not statistically significant, indicating that this measurement of employment may not have a large impact on perceptions of Chinese loans. Overall, the plot and regression analysis highlights that education plays a significant role in shaping public opinion on foreign debt. The results show that higher education, particularly in combination with the perception of high national debt, leads to a higher probability of viewing Chinese loans as a problem. These findings confirm the hypothesis that access to information—through education—significantly conditions individuals’ responses to Chinese loans.</p>
<p>Conclusion:</p>
<p>For Africans surveyed in the Afrobarometer 2022 Round 8 Survey we find some evidence that education, particularly in combination with perceptions of national debt, plays a significant role in shaping individuals’ views on Chinese loans. The analysis shows that individuals with higher education and a high perception of debt are more likely to view Chinese loans as problematic. This relationship is evident both in the regression model and the predicted probabilities, with a clear pattern emerging. Employment status also plays a role, with individuals seeking work being less likely to view these loans negatively, possibly due to more immediate economic concerns. The study highlights the potential for African countries to strategically leverage education, transparency, and information access to navigate complex international relationships. By prioritizing these factors, African governments can better manage foreign partnerships and secure more balanced and equitable agreements that safeguard the welfare of future generations. This analysis focuses on education and debt perception, but other factors—such as political ideology or media exposure—heavily influence opinions. Future research would benefit from incorporating these variables and expanding the scope to include longitudinal data, providing stronger evidence on how education and information affect public opinion over time. While the insight that education and information access shape public opinion is not groundbreaking, the unique contribution of this study lies in its specific focus on how education and debt perception, in particular, interact to influence views on Chinese loans in Africa. Instead of merely recognizing that more information leads to better-informed opinions, this study emphasizes how individuals’ educational background and perceptions of national debt work together to shape their opinions on Chinese loans. This nuance gives a more comprehensive understanding of how African citizens evaluate Chinese loans in a complex geopolitical context.</p>
<p>#Appendix</p>
<p>This appendeix contains the questions used for covariates in the study: Education level, Employment, Region, Trust in President.</p>
<p>Question Number: Q97 Question: What is your highest level of education? Variable Label: Q97. Education of respondent Values: 0-9, 98, 99, -1 Value Labels: 0=No formal schooling, 1=Informal schooling only (including Koranic schooling), 2=Some primary schooling, 3=Primary school completed, 4=Intermediate school or some secondary school/high school, 5=Secondary school/high school completed, 6=Post-secondary qualifications, other than university, 7=Some university, 8=University completed, 9=Post-graduate, 98=Refused, 99=Don’t know, -1=Missing Source: SAB</p>
<p>Question Number: Q95A Question: Do you have a job that pays a cash income? [If yes, ask] Is it full-time or part-time? [If no, ask:] Are you presently looking for a job? Variable Label: Q95a. Employment status Values: 0-3, 8, 9, -1 Value Labels: 0=No, not looking, 1=No, looking, 2=Yes, part time, 3=Yes, full time, 8=Refused, 9=Don’t know, -1=Missing Source: Afrobarometer Round 5</p>
<p>Question Number: Q95C Question: What is your main occupation? [If unemployed, retired, or disabled, ask:] What was your last main occupation? Variable Label: Q95c. Occupation of respondent Values: 0-12, 220, 700, 1500, 15800, 1700, 95, 98, 99, -1 Value Labels: 0=Never had a job, 1=Student, 2=Housewife/homemaker, 3=Agriculture/farming/fishing/ forestry, 4=Trader/hawker/vendor, 5=Retail/shop, 6=Unskilled manual worker, 7=Artisan or skilled manual worker, 8=Clerical or secretarial, 9=Supervisor/foreman/senior manager, 10=Security services, 11=Mid-level professional, 12=Upper-level professional, 220=Retired, 700=Self-employed/Business Owner, 1500=Retired, 1580=Retired, 1700=RETRAITÉ, 95=Other, 98=Refused, 99=Don’t know, -1=Missing Source: SAB</p>
<p>Question Number: REGION Question: Region/Province Variable Label: Province or region Values: 100-111, 140-164, 180-192, 220-224, 260-275, 300-346, 350-359, 380-394, 460-462, 501-509, 540-550, 580-593, 620-673, 700-708, 740-770, 780-792, 820-829, 860-869, 900-909, 930-933, 1100-1107, 1140-1145, 1221- 1232, 1260-1292, 1300-1307, 1340-1350, 1500-1511, 1540-1545, 1580-1586, 1620-1623, 1700-1708, 1740-1747, 1780-1797</p>
<p>Question Number: Q41A Question: How much do you trust each of the following, or haven’t you heard enough about them to say: The President? Variable Label: Q41a. Trust president Values: 0-3, 8, 9, -1 Value Labels: 0=Not at all, 1=Just a little, 2=Somewhat, 3=A lot, 8=Refused, 9=Don’t know/Haven’t heard, - 1=Missing Source: Zambia96</p>
<p>“Does a respondent’s opinion on Chinese debt predict how much aid their area received, controlling for other factors like education, employment, and trust in the president?”</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>